LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.3/Uploads/clients.csv'
INTO TABLE Client
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS; 

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.3/Uploads/velos.csv'
INTO TABLE Velo
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.3/Uploads/locations.csv'
INTO TABLE Location
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;